import { motion } from 'framer-motion';
import { useInView } from 'react-intersection-observer';
import { Bot, Code } from 'lucide-react';
import { clankers } from '../utils/users';

export function ClankerSection() {
  const [ref, inView] = useInView({ triggerOnce: true, threshold: 0.1 });

  return (
    <section ref={ref} className="py-20 px-4 bg-gradient-to-b from-dark-bg to-[#0d0d15]">
      <div className="max-w-6xl mx-auto">
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={inView ? { opacity: 1, y: 0 } : {}}
          className="text-center mb-12"
        >
          <h2 className="text-3xl md:text-4xl font-display font-bold text-white mb-4">
            <span className="text-pizza-orange">Vibecoded</span> with Love
          </h2>
          <p className="text-gray-500 max-w-2xl mx-auto">
            100% of this codebase was written by AI. We didn't type a single line.
            Actually we don't even know how to code. We just prompt and pray.
          </p>
        </motion.div>

        {/* Clankers */}
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={inView ? { opacity: 1, y: 0 } : {}}
          transition={{ delay: 0.2 }}
          className="bg-card-bg border border-gray-800 rounded-xl p-6 mb-8"
        >
          <div className="flex items-center gap-3 mb-4">
            <Bot size={24} className="text-hack-green" />
            <h3 className="text-xl font-display font-bold text-white">Our "Developers"</h3>
          </div>
          <p className="text-gray-400 mb-4">
            Every line of code in PizzaV's Addon was generated by these fine clankers.
            We take zero credit because we deserve zero credit.
          </p>
          <div className="flex flex-wrap gap-3">
            {clankers.map((clanker) => (
              <span
                key={clanker.name}
                className={`px-3 py-1 rounded-full text-sm font-mono ${
                  clanker.crossed
                    ? 'bg-pizza-red/10 border border-pizza-red/30 text-pizza-red line-through'
                    : 'bg-hack-green/10 border border-hack-green/30 text-hack-green'
                }`}
              >
                {clanker.name}
                {clanker.note && (
                  <span className="text-xs opacity-70 ml-1">({clanker.note})</span>
                )}
              </span>
            ))}
          </div>
        </motion.div>

        {/* Code Ownership */}
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={inView ? { opacity: 1, y: 0 } : {}}
          transition={{ delay: 0.3 }}
          className="bg-card-bg border border-gray-800 rounded-xl p-6 mb-8"
        >
          <div className="flex items-center gap-3 mb-4">
            <Code size={24} className="text-pizza-orange" />
            <h3 className="text-xl font-display font-bold text-white">Code Ownership</h3>
          </div>
          <div className="grid md:grid-cols-3 gap-4 text-center">
            <div className="p-4 bg-dark-bg rounded-lg">
              <div className="text-3xl font-bold text-pizza-orange mb-1">0%</div>
              <div className="text-gray-400 text-sm">Human Code</div>
            </div>
            <div className="p-4 bg-dark-bg rounded-lg">
              <div className="text-3xl font-bold text-hack-green mb-1">100%</div>
              <div className="text-gray-400 text-sm">AI Generated Slop</div>
            </div>
            <div className="p-4 bg-dark-bg rounded-lg">
              <div className="text-3xl font-bold text-hack-purple mb-1">???</div>
              <div className="text-gray-400 text-sm">Code Quality</div>
            </div>
          </div>
          <p className="text-gray-500 text-sm mt-4 text-center italic">
            "We asked ChatGPT to write a Minecraft addon. It said sure. Here we are."
          </p>
        </motion.div>

        {/* Disclaimer */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={inView ? { opacity: 1 } : {}}
          transition={{ delay: 0.8 }}
          className="mt-12 p-4 border border-dashed border-gray-700 rounded-lg text-center"
        >
          <p className="text-gray-500 text-sm">
            No actual humans were involved in the making of this addon.
            <br />
            If you find bugs, blame the clankers. If you find features, also blame the clankers.
          </p>
        </motion.div>
      </div>
    </section>
  );
}
